version: '3'

services:
  db:
    image: postgres
    restart: always
  web:
    build: .
    restart: always
    environment:
      ALLOWED_HOSTS: localhost 
      SECRET_KEY: abcd
      DEBUG: "True"
      SENTRY_DSN: ""
      B_DATABASE_URL: postgres://postgres:@db:5432/postgres
      WAIT_FOR: db:5432
    command: ./run_dev_server.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
